[package]
publish = false
repository = "https://github.com/soydanil/kn"
description = "Núcleo local de versiones y worktrees para kn"
name = "kn-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tempfile.workspace = true
thiserror = "2"
fs2 = "0.4"
ureq = "3"
sha2 = "0.10"
base64 = "0.22"
getrandom = "0.3"
keyring = { version = "3", default-features = false, features = ["apple-native", "windows-native", "linux-native"] }

[dev-dependencies]
tiny_http = "0.12"
